### ISSUE TITLE
[ALTA] Desenvolver a personalidade do cavalo protagonista

### ISSUE THREAD

**Issue by durvalcarvalho** [MarthaDs/TreinaBolinho#2]
- Definir as características físicas e a personalidade
- Definir histórico do personagem (vida pregressa)
- Definir motivações do personagem

**Comment by durvalcarvalho** [comment]
Eu como leitor, gostaria de desenvolver empatia com o personagem principal e ser capaz de entender as motivações do protagonista.

**Comment by LeoSilvaGomes-zz** [comment]
Indo sprint 2

**Comment by durvalcarvalho** [comment]
Concluída
