### ISSUE TITLE
[ALTA]Desenvolver o personagem par romântico do protagonista.

### ISSUE THREAD

**Issue by jps12** [MarthaDs/TreinaBolinho#3]
- Prioridade alta.
- Definir caracteristicas físicas.
- Definir caracteristicas psicológicas.

**Comment by jps12** [comment]
- Divida técnica da sprint 1 tá indo para a sprint 2.

**Comment by jps12** [comment]
issue concluida com sucesso

**Comment by LeoSilvaGomes-zz** [comment]
Issue concluida com sucesso
