### ISSUE TITLE
[ALTA] Desenvolver enredo 

### ISSUE THREAD

**Issue by KiSobral** [MarthaDs/TreinaBolinho#5]
- Relação entre personagens
- Personagens inseridos no contexto do faroeste

Dependência: Issue de desenvolver a personalidade das personagens

**Comment by KiSobral** [comment]
Divida técnica da sprint 1 
Issue encaminhada para sprint 2

**Comment by LeoSilvaGomes-zz** [comment]
Issue concluida com sucesso
